# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.35.1
# 

Name:       plocate

# >> macros
# << macros
%define sgid_group privileged
%define dbloc %{_localstatedir}/cache
%define dbname %{dbloc}/%{name}.db
%define debug_build 0

Summary:    A locate/updatedb implementation
Version:    1.1.23
Release:    0
Group:      Applications/File
License:    GPLv2
URL:        https://plocate.sesse.net/
Source0:    %{name}-%{version}.tar.gz
Source1:    %{name}-updatedb.conf
Source2:    %{name}-updatedb.service
Source3:    %{name}-updatedb.timer
Source4:    %{name}-updatedb-user.service
Source5:    %{name}-updatedb-user.timer
Source6:    plocate-migrate-mlocate-db
Source100:  plocate.yaml
Requires(post): %{_libexecdir}/manage-groups
Requires(postun): %{_libexecdir}/manage-groups
BuildRequires:  pkgconfig(libzstd)
BuildRequires:  cmake
BuildRequires:  meson
BuildRequires:  meson
Conflicts:   harbour-mlocate
Conflicts:   mlocate
Obsoletes:   harbour-mlocate < 0.27
Obsoletes:   mlocate < 0.27

%description
plocate is a locate(1) based on posting lists, completely replacing mlocate
with a much faster (and smaller) index. It is suitable as a default locate
on your system.

%if "0%{?_chum}"
PackageName: plocate
Type: console-application
Categories:
 - Utility
 - FileTools
Custom:
  Repo: https://git.sesse.net/?p=plocate
  PackagingRepo: https://github.com/sailfishos-chum/plocate
Url:
  Homepage: https://plocate.sesse.net/
%endif


%package service-user
Summary:    User timer for updatedb
Group:      System/Daemons
BuildArch:  noarch
Requires:   %{name} = %{version}-%{release}
Requires(post): systemd
Conflicts:  harbour-mlocate-systemd-user
Conflicts:  mlocate-service-user
Obsoletes:  harbour-mlocate-systemd-user
Obsoletes:  mlocate-service-user

%description service-user
Adds SystemD timer and service users can enable which will index only
their HOME and keep the database under ~/.cache


%package service-system
Summary:    System timer for updatedb
Group:      System/Daemons
BuildArch:  noarch
Requires:   %{name} = %{version}-%{release}
Requires(post): systemd
Conflicts:  harbour-mlocate-systemd-system
Conflicts:  mlocate-service-system
Obsoletes:  harbour-mlocate-systemd-system
Obsoletes:  mlocate-service-system

%description service-system
Adds SystemD timer and service which will keep the index up-to-date


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%meson  \
    -Dinstall_cron=false \
    -Dinstall_systemd=true \
    -Dsystemunitdir=%{_unitdir} \
    -Dlocategroup=%{sgid_group}

%meson_build

# >> build post
# << build post

%install
# >> install pre
# << install pre
%meson_install

# >> install post
%{__install} -p -D -m 644 %{S:1} %{buildroot}/%{_sysconfdir}/updatedb.conf
%{__install} -p -D -m 644 %{S:2} %{buildroot}/%{_unitdir}/%{name}-updatedb.service
%{__install} -p -D -m 644 %{S:3} %{buildroot}/%{_unitdir}/%{name}-updatedb.timer
%{__install} -p -D -m 644 %{S:4} %{buildroot}/%{_userunitdir}/%{name}-updatedb-user.service
%{__install} -p -D -m 644 %{S:5} %{buildroot}/%{_userunitdir}/%{name}-updatedb-user.timer
# << install post

%preun
# >> preun
%systemd_preun %{name}-updatedb.service
%systemd_user_preun %{name}-updatedb-user.service
# << preun

%post
# >> post
# See https://github.com/sailfishos/sailfish-setup/blob/master/scripts/manage-groups.sh
%{_libexecdir}/manage-groups add %{sgid_group} || :

%post service-system
systemctl enable %{name}-updatedb.timer || :
%systemd_post %{name}-updatedb.service ||:

%post service-user
%systemd_user_post %{name}-updatedb-user.service ||:
# << post

%postun
# >> postun
# See https://github.com/sailfishos/sailfish-setup/blob/master/scripts/manage-groups.sh
if [ "$1" -eq 0 ]; then
%{_libexecdir}/manage-groups remove %{sgid_group} || :
fi

%postun service-system
%systemd_postun %{name}-updatedb.service
%systemd_postun %{name}-updatedb.timer
if [ $1 = 0 ]; then
#Do stuff specific to uninstalls
rm -f %{dbname} || :
else
if [ $1 = 1 ]; then
#Do stuff specific to upgrades
echo "this is an upgrade..."
if [ -e %{dbname} ]; then
/bin/chgrp -cv %{sgid_group} %{dbname} || :
fi
fi
fi
systemctl daemon-reload >/dev/null 2>&1 || :

%postun service-user
%systemd_user_postun %{name}-updatedb-user.service
%systemd_user_postun %{name}-updatedb-user.timer
%systemd_postun
# << postun

%files
%{_bindir}/plocate
%{_sbindir}/plocate-build
%{_sbindir}/updatedb
%config %{_sysconfdir}/updatedb.conf
%attr(2711,root,%{sgid_group}) %{_bindir}/plocate
%{_localstatedir}/lib/%{name}/CACHEDIR.TAG
%ghost %{_localstatedir}/lib/%{name}/%{name}.db
%exclude %{_mandir}/*
# >> files
# << files

%files service-user
%{_userunitdir}/%{name}-updatedb-user.service
%{_userunitdir}/%{name}-updatedb-user.timer
# >> files service-user
# << files service-user

%files service-system
%{_unitdir}/%{name}-updatedb.service
%{_unitdir}/%{name}-updatedb.timer
# >> files service-system
# << files service-system
